trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  kubernetesCluster: 'acm-aks'
  azureResourceGroup: 'acm'
  azureSubscription: 'Pay-As-You-Go(6b3b2d60-1ccd-486e-b6be-0fc7107fc463)'

steps:
- task: DockerInstaller@0
  inputs:
    dockerVersion: '18.06.1-ce'
- task: HelmInstaller@1
  inputs:
    helmVersionToInstall: 'latest'

- script: docker login -u $DOCKER_USER -p $DOCKER_PASS acmregistry2019.azurecr.io
  displayName: 'Login'

- script: ./src/AuthApplication/Scripts/docker-build-push.sh
  displayName: 'Build and Push Auth Application'

- script: ./src/CatalogApplication/Scripts/docker-build-push.sh
  displayName: 'Build and Push Catalog Application'

- script: ./src/ClassApplication/Scripts/docker-build-push.sh
  displayName: 'Build and Push Class Application'

- script: ./src/NotesApplication/Scripts/docker-build-push.sh
  displayName: 'Build and Push Notes Application'

- task: HelmDeploy@0
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: '$(azureSubscription)'
    azureResourceGroup: '$(azureResourceGroup)'
    kubernetesCluster: '$(kubernetesCluster)'
    useClusterAdmin: true
    namespace: 'dev'
    command: 'init'
    arguments: '--wait'

- task: HelmDeploy@0
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: '$(azureSubscription)'
    azureResourceGroup: '$(azureResourceGroup)'
    kubernetesCluster: '$(kubernetesCluster)'
    useClusterAdmin: true
    namespace: 'dev'
    command: 'upgrade'
    chartType: 'FilePath'
    chartPath: './src/charts/.'
    releaseName: 'platform'
    waitForExecution: false
