# https://dev.azure.com
#
# Build, Test and Deploys the AuthApplication to Production

trigger:
  paths:
    include:
      - src/Shared/Sdk/*

resources:
  - repo: self

jobs:
  - job: UnitTestSdk
    displayName: Unit Test for SDK
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - task: DotNetCoreInstaller@0
        inputs:
          version: "2.1.802"
      - script: dotnet test src/Shared/Sdk.Test

  - job: UnitTestNeptune
    displayName: Unit Test for Neptune
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - task: DotNetCoreInstaller@0
        inputs:
          version: "2.1.802"
      - script: dotnet test src/Shared/Neptune.Tests

  - job: PublishSdk
    dependsOn:
      - UnitTestSdk
    condition: and(succeeded('UnitTestSdk'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: Publish Sdk
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - task: DotNetCoreInstaller@0
        inputs:
          version: "2.1.802"
      - script: Version=$(sed -ne '/Version/{s/.*<Version>\(.*\)<\/Version>.*/\1/p;q;}' <<< cat ./src/Shared/Sdk/Sdk.csproj)
      - script: dotnet pack ./src/Shared/Sdk/Sdk.csproj
      - script: dotnet nuget push ./src/Shared/Sdk/bin/Debug/ACMTTU.NoteSharing.Shared.SDK.$Version.nupkg -k $(API_KEY) -s https://api.nuget.org/v3/index.json

  - job: PublishNeptune
    dependsOn:
      - UnitTestNeptune
    condition: and(succeeded('UnitTestNeptune'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: Publish Neptune
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - task: DotNetCoreInstaller@0
        inputs:
          version: "2.1.802"
      - script: Version=$(sed -ne '/Version/{s/.*<Version>\(.*\)<\/Version>.*/\1/p;q;}' <<< cat ./src/Shared/Neptune/Neptune.csproj)
      - script: dotnet pack ./src/Shared/Neptune/Neptune.csproj
      - script: dotnet nuget push ./src/Shared/Neptune/bin/Debug/ACMTTU.NoteSharing.Shared.Neptune.$Version.nupkg -k $(API_KEY) -s https://api.nuget.org/v3/index.json
