# https://dev.azure.com

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  kubernetesCluster: 'acm-notes-aks'
  azureResourceGroup: 'acm-notes'
  azureSubscription: 'Pay-As-You-Go(6b3b2d60-1ccd-486e-b6be-0fc7107fc463)'

steps:
- task: DockerInstaller@0
  inputs:
    dockerVersion: '18.06.1-ce'
- task: HelmInstaller@1
  inputs:
    helmVersionToInstall: 'latest'

- script: docker login -u $(DOCKER_USER) -p $(DOCKER_PASS) acmnotesregistry.azurecr.io
  displayName: 'Login'

- script: az acr build -t acmnotesregistry.azurecr.io/authapplication:stable ./src/AuthApplication
  displayName: 'Build and Push Auth Application'

- script: az acr build -t acmnotesregistry.azurecr.io/catalogapplication:stable ./src/CatalogApplication
  displayName: 'Build and Push Catalog Application'

- script: az acr build -t acmnotesregistry.azurecr.io/classapplication:stable ./src/ClassApplication
  displayName: 'Build and Push Class Application'

- script: az acr build -t acmnotesregistry.azurecr.io/notesapplication:stable ./src/NotesApplication
  displayName: 'Build and Push Notes Application'

- script: az aks get-credentials --admin -g acm-notes -n acm-notes-aks --overwrite-existing
  displayName: 'Get Credentials for Kubernetes Cluster'

- task: HelmDeploy@0
  displayName: Helm Init
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: '$(azureSubscription)'
    azureResourceGroup: '$(azureResourceGroup)'
    kubernetesCluster: '$(kubernetesCluster)'
    useClusterAdmin: true
    namespace: 'dev'
    command: 'init'
    arguments: '--service-account tiller --history-max 200 --wait'

- task: HelmDeploy@0
  displayName: Helm Deploy
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: '$(azureSubscription)'
    azureResourceGroup: '$(azureResourceGroup)'
    kubernetesCluster: '$(kubernetesCluster)'
    command: upgrade
    arguments: platform ./src/charts/. -i --namespace dev 
