# https://dev.azure.com
#
# Build, Test and Deploys the ClassApplication to Production

trigger:
  paths:
    include:
      - src/ClassApplication/*

resources:
  - repo: self

variables:
  kubernetesCluster: "notes-app-aks"
  azureResourceGroup: "notes-app"

jobs:
  - job: UnitTest
    displayName: Test Image
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - task: DotNetCoreInstaller@0
        inputs:
          version: "2.1.802"
      - script: dotnet build ./src/ClassApplication/ClassApplication.csproj && dotnet test ./src/ClassApplication/ClassApplication.csproj

  - job: PushAndDeployImage
    dependsOn:
      - UnitTest
    condition: and(succeeded('UnitTest'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: Push And Deploy Image
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - task: DockerInstaller@0
        inputs:
          dockerVersion: "18.06.1-ce"

      - task: HelmInstaller@1
        inputs:
          helmVersionToInstall: "latest"

      - script: docker login -u $(DOCKER_USER) -p $(DOCKER_PASS) notesappregistry.azurecr.io
        displayName: "Login"

      - script: ./src/ClassApplication/Scripts/docker-build-push.sh
        displayName: "Build and Push Class Application"

      - task: HelmDeploy@0
        displayName: Helm Init
        inputs:
          connectionType: "Azure Resource Manager"
          azureSubscriptionEndpoint: "$(AZURE_SUBSCRIPTION)"
          azureResourceGroup: "$(azureResourceGroup)"
          kubernetesCluster: "$(kubernetesCluster)"
          useClusterAdmin: true
          namespace: "dev"
          command: "init"
          arguments: "--service-account tiller --history-max 200 --wait"

      - task: HelmDeploy@0
        displayName: Helm Deploy to Staging/Dev Space
        inputs:
          connectionType: "Azure Resource Manager"
          azureSubscriptionEndpoint: "$(AZURE_SUBSCRIPTION)"
          azureResourceGroup: "$(azureResourceGroup)"
          kubernetesCluster: "$(kubernetesCluster)"
          chartName: "./src/ClassApplication/charts/classapplication"
          releaseName: "classapplication"
          command: upgrade
          arguments: -i --force --namespace dev
