# https://dev.azure.com
#
# Build, Test and Deploys the AuthApplication to Production

trigger:
  paths:
    include:
      - src/Shared/Sdk/*

resources:
  - repo: self

jobs:
  - job: UnitTest
    displayName: Build Image
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - task: DotNetCoreInstaller@0
        inputs:
          version: "2.1.802"
      - script: dotnet test src/Shared/Sdk.Test

  - job: PublishNugetPackage
    dependsOn:
      - UnitTest
    condition: and(succeeded('UnitTest'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: Publish Nuget Package
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - task: DotNetCoreInstaller@0
        inputs:
          version: "2.1.802"
      - script: Version=$(sed -ne '/Version/{s/.*<Version>\(.*\)<\/Version>.*/\1/p;q;}' <<< cat src/Shared/Sdk/Sdk.csproj)
      - script: dotnet pack src/Shared/SDK.csproj
      - script: dotnet nuget push src/Shared/SDK/bin/Debug/ACMTTU.NoteSharing.Shared.SDK.$VERSION.nupkg -k $(API_KEY) -s https://api.nuget.org/v3/index.json
