apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "secretsservice.fullname" . }}
  labels:
    app: {{ template "secretsservice.name" . }}
    chart: {{ template "secretsservice.chart" . }}
    draft: {{ .Values.draft | default "draft-app" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "secretsservice.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "secretsservice.name" . }}
        draft: {{ .Values.draft | default "draft-app" }}
        release: {{ .Release.Name }}
      annotations:
        buildID: {{ .Values.buildID | default "" | quote }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          volumeMounts:
          - name: keyvaultvolume
            mountPath: /kvmnt
            readOnly: true
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          {{- if .Values.probes.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- end }}
          env:
            {{- $root := . }}
            {{- range $ref, $values := .Values.secrets }}
            {{- range $key, $value := $values }}
            - name: {{ $ref }}_{{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ template "secretsservice.fullname" $root }}-{{ $ref | lower }}
                  key: {{ $key }}
            {{- end }}
            {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
        - name: keyvaultvolume
          flexVolume:
            driver: "azure/kv"
            secretRef:
              name: notesappkvcreds
            options:
              usepodidentity: "false"
              keyvaultname: "notes-app-kv"
              keyvaultobjectnames: database-dev;database-staging;database-prod;blobstorage-dev;blobstorage-staging;blobstorage-prod
              keyvaultobjecttypes: secret;secret;secret;secret;secret;secret
              keyvaultobjectversions: ""
              resourcegroup: "notes-app"
              subscriptionid: "9c16434b-4aa3-4e38-9bda-d68d192f9b2c"
              tenantid: "b1fc7d22-90e3-4945-b4cf-737eedb2905e"
