export resourceGroupName="notes-app"
export subscriptionId="9c16434b-4aa3-4e38-9bda-d68d192f9b2c"
export appId="App ID Goes Here"
export clientSecret="Secret Goes Here"
export vaultName="notes-app-kv"